2024/01/01 05:40:41 [error] 1022#1022: *254 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/yWBH1be6KjUGUA-o-iK35ZMDgXTA0bt0dhC3apugl-Q" failed (2: No such file or directory), client: 35.92.145.233, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/yWBH1be6KjUGUA-o-iK35ZMDgXTA0bt0dhC3apugl-Q HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/yWBH1be6KjUGUA-o-iK35ZMDgXTA0bt0dhC3apugl-Q"
2024/01/01 05:40:42 [error] 1022#1022: *255 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/yWBH1be6KjUGUA-o-iK35ZMDgXTA0bt0dhC3apugl-Q" failed (2: No such file or directory), client: 3.128.255.252, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/yWBH1be6KjUGUA-o-iK35ZMDgXTA0bt0dhC3apugl-Q HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/yWBH1be6KjUGUA-o-iK35ZMDgXTA0bt0dhC3apugl-Q"
2024/01/01 05:40:42 [error] 1022#1022: *256 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/yWBH1be6KjUGUA-o-iK35ZMDgXTA0bt0dhC3apugl-Q" failed (2: No such file or directory), client: 23.178.112.202, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/yWBH1be6KjUGUA-o-iK35ZMDgXTA0bt0dhC3apugl-Q HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/yWBH1be6KjUGUA-o-iK35ZMDgXTA0bt0dhC3apugl-Q"
2024/01/01 06:34:55 [error] 1275#1275: *1300 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/lBTYpNqeLxPTVDKkRysSw1U5pFjOzaUF0eChZs-lE9g" failed (2: No such file or directory), client: 23.178.112.108, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/lBTYpNqeLxPTVDKkRysSw1U5pFjOzaUF0eChZs-lE9g HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/lBTYpNqeLxPTVDKkRysSw1U5pFjOzaUF0eChZs-lE9g"
2024/01/01 06:34:55 [error] 1275#1275: *1301 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/lBTYpNqeLxPTVDKkRysSw1U5pFjOzaUF0eChZs-lE9g" failed (2: No such file or directory), client: 3.128.255.252, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/lBTYpNqeLxPTVDKkRysSw1U5pFjOzaUF0eChZs-lE9g HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/lBTYpNqeLxPTVDKkRysSw1U5pFjOzaUF0eChZs-lE9g"
2024/01/01 06:34:55 [error] 1275#1275: *1302 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/lBTYpNqeLxPTVDKkRysSw1U5pFjOzaUF0eChZs-lE9g" failed (2: No such file or directory), client: 34.220.222.78, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/lBTYpNqeLxPTVDKkRysSw1U5pFjOzaUF0eChZs-lE9g HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/lBTYpNqeLxPTVDKkRysSw1U5pFjOzaUF0eChZs-lE9g"
2024/01/01 07:38:16 [error] 1521#1521: *1350 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/Yfr8-VAOT8CAX7Tk6ZSFhMBlmFEtx4Yst3egKzW5R2E" failed (2: No such file or directory), client: 34.220.222.78, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/Yfr8-VAOT8CAX7Tk6ZSFhMBlmFEtx4Yst3egKzW5R2E HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/Yfr8-VAOT8CAX7Tk6ZSFhMBlmFEtx4Yst3egKzW5R2E"
2024/01/01 07:38:16 [error] 1521#1521: *1351 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/Yfr8-VAOT8CAX7Tk6ZSFhMBlmFEtx4Yst3egKzW5R2E" failed (2: No such file or directory), client: 3.128.255.252, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/Yfr8-VAOT8CAX7Tk6ZSFhMBlmFEtx4Yst3egKzW5R2E HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/Yfr8-VAOT8CAX7Tk6ZSFhMBlmFEtx4Yst3egKzW5R2E"
2024/01/01 07:38:16 [error] 1521#1521: *1352 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/Yfr8-VAOT8CAX7Tk6ZSFhMBlmFEtx4Yst3egKzW5R2E" failed (2: No such file or directory), client: 23.178.112.202, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/Yfr8-VAOT8CAX7Tk6ZSFhMBlmFEtx4Yst3egKzW5R2E HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/Yfr8-VAOT8CAX7Tk6ZSFhMBlmFEtx4Yst3egKzW5R2E"
2024/01/01 08:39:36 [error] 1772#1772: *1413 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/Wea-FFEbb1Mx9aCmZi1LKF-dGV4LMxdtxoydgLsGByo" failed (2: No such file or directory), client: 3.128.255.252, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/Wea-FFEbb1Mx9aCmZi1LKF-dGV4LMxdtxoydgLsGByo HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/Wea-FFEbb1Mx9aCmZi1LKF-dGV4LMxdtxoydgLsGByo"
2024/01/01 08:39:36 [error] 1772#1772: *1414 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/Wea-FFEbb1Mx9aCmZi1LKF-dGV4LMxdtxoydgLsGByo" failed (2: No such file or directory), client: 35.92.145.233, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/Wea-FFEbb1Mx9aCmZi1LKF-dGV4LMxdtxoydgLsGByo HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/Wea-FFEbb1Mx9aCmZi1LKF-dGV4LMxdtxoydgLsGByo"
2024/01/01 08:39:36 [error] 1772#1772: *1415 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/Wea-FFEbb1Mx9aCmZi1LKF-dGV4LMxdtxoydgLsGByo" failed (2: No such file or directory), client: 23.178.112.103, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/Wea-FFEbb1Mx9aCmZi1LKF-dGV4LMxdtxoydgLsGByo HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/Wea-FFEbb1Mx9aCmZi1LKF-dGV4LMxdtxoydgLsGByo"
2024/01/01 09:39:20 [error] 2020#2020: *1467 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/SMtsQy1VNTnXRaJW1nh6G6Ez9gS1Gsz7uv9oOU1FUiE" failed (2: No such file or directory), client: 34.220.222.78, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/SMtsQy1VNTnXRaJW1nh6G6Ez9gS1Gsz7uv9oOU1FUiE HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/SMtsQy1VNTnXRaJW1nh6G6Ez9gS1Gsz7uv9oOU1FUiE"
2024/01/01 09:39:20 [error] 2020#2020: *1468 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/SMtsQy1VNTnXRaJW1nh6G6Ez9gS1Gsz7uv9oOU1FUiE" failed (2: No such file or directory), client: 3.144.190.229, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/SMtsQy1VNTnXRaJW1nh6G6Ez9gS1Gsz7uv9oOU1FUiE HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/SMtsQy1VNTnXRaJW1nh6G6Ez9gS1Gsz7uv9oOU1FUiE"
2024/01/01 09:39:20 [error] 2020#2020: *1469 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/SMtsQy1VNTnXRaJW1nh6G6Ez9gS1Gsz7uv9oOU1FUiE" failed (2: No such file or directory), client: 23.178.112.204, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/SMtsQy1VNTnXRaJW1nh6G6Ez9gS1Gsz7uv9oOU1FUiE HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/SMtsQy1VNTnXRaJW1nh6G6Ez9gS1Gsz7uv9oOU1FUiE"
2024/01/01 12:46:55 [error] 3011#3011: *2557 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/7ub4jNmoplHzcp73pIzRDck6QXCP3FlnoJf0mAndh2o" failed (2: No such file or directory), client: 3.128.255.252, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/7ub4jNmoplHzcp73pIzRDck6QXCP3FlnoJf0mAndh2o HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/7ub4jNmoplHzcp73pIzRDck6QXCP3FlnoJf0mAndh2o"
2024/01/01 12:46:55 [error] 3011#3011: *2558 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/7ub4jNmoplHzcp73pIzRDck6QXCP3FlnoJf0mAndh2o" failed (2: No such file or directory), client: 23.178.112.105, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/7ub4jNmoplHzcp73pIzRDck6QXCP3FlnoJf0mAndh2o HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/7ub4jNmoplHzcp73pIzRDck6QXCP3FlnoJf0mAndh2o"
2024/01/01 12:46:55 [error] 3011#3011: *2559 open() "/data/letsencrypt-acme-challenge/.well-known/acme-challenge/7ub4jNmoplHzcp73pIzRDck6QXCP3FlnoJf0mAndh2o" failed (2: No such file or directory), client: 35.92.145.233, server: nextcloud.hanisntsolo.online, request: "GET /.well-known/acme-challenge/7ub4jNmoplHzcp73pIzRDck6QXCP3FlnoJf0mAndh2o HTTP/1.1", host: "nextcloud.hanisntsolo.online", referrer: "http://nextcloud.hanisntsolo.online/.well-known/acme-challenge/7ub4jNmoplHzcp73pIzRDck6QXCP3FlnoJf0mAndh2o"
